# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-16 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='members', to='main.UserProfile'),
        ),
    ]
