# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-17 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170117_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_message', to='main.Message'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(null=True, related_name='members', to='main.UserProfile'),
        ),
    ]
