# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 07:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170117_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_joined', models.DateTimeField(default=datetime.datetime.now)),
                ('time_left', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dp',
            field=models.ImageField(null=True, upload_to=b'dps'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dp_url',
            field=models.SlugField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lat',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='locality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.RemoveField(
            model_name='group',
            name='message',
        ),
        migrations.AddField(
            model_name='group',
            name='message',
            field=models.ManyToManyField(null=True, related_name='group_message', to='main.Message'),
        ),
        migrations.AddField(
            model_name='group_user',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_group_time', to='main.Group'),
        ),
        migrations.AddField(
            model_name='group_user',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_user_time', to='main.UserProfile'),
        ),
    ]
